/* (c) https://github.com/MontiCore/monticore */

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    id "java"
    id "maven-publish"
    id "de.monticore.generator-withtr" version "$mc_version" // MontiCore Plugin with TR support
    id "com.gradleup.shadow" version "$shadow_plugin_version"
    id "io.github.themrmilchmann.ecj" version "0.2.0"
}

description = "Statecharts"
layout.buildDirectory = layout.projectDirectory.dir("target")


def testSCOutDir = layout.buildDirectory.dir("generated-test-sources/sc").get().asFile.absolutePath
def testSCGenDir  = layout.projectDirectory.dir("src/testscgen").asFile.absolutePath

def withTR = ("true").equals(getProperty('genTR'));

// configure non-standard source sets
sourceSets {
  main { }
  test { }
  // The following is required as we still publish a Feature-variant (with usingSourceSet(grammarsForVariant))
  grammarsForVariant {
    java.srcDirs = []
    resources {
      // DO not include the grammars out dir here (with the TR grammars)
      srcDirs(["src/main/grammars"])
      include "**/*.mc4"
      include "**/*.mlc"
    }
    grammars.srcDirs = []
  }

  testscgen {
    java.srcDirs += ["$testSCOutDir"]

    java {}
  }
}

configurations {
  testscgenImplementation.extendsFrom(implementation)
  testscgenImplementation.extendsFrom(testImplementation)
  trafoGrammar // this configuration is actually further set up by the generator-withtr plugin
  if (withTR) {
    umlscTransGenerator {
      canBeConsumed = true
      canBeResolved = false
    }
  }
}

dependencies {
  // Depend on the monticore component grammars
  grammar("de.monticore:monticore-grammar:$mc_version")
  // and their respective trafo-components (as a grammar dependency of the trafo source set)
  trafoGrammar grammar("de.monticore:monticore-grammar-trafo:$mc_version")

  // normal, implementation dependencies
  implementation "de.monticore:class2mc:$mc_version"
  implementation "de.monticore.lang:cd4analysis:$mc_version"
  implementation "org.apache.commons:commons-lang3:$commons_lang3_version"
  implementation "org.apache.groovy:groovy:$groovy_version"
  testImplementation "org.junit.jupiter:junit-jupiter:$junit_version"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher"

  testscgenImplementation(sourceSets.main.output.classesDirs)
  testscgenImplementation(sourceSets.test.output.classesDirs)
}

repositories {
    if (("true").equals(getProperty('useLocalRepo'))) {
        mavenLocal()
    }
    maven {
        credentials.username = mavenUser
        credentials.password = mavenPassword
        url = repo
    }
}

// Use Java21
allprojects {
  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(21)
    }
  }
  ecj {
    compilerVersion = "3.43.0"
  }
}


test {
  useJUnitPlatform()
}


// A Task using the UMLStatechartsTool
tasks.register('generateSC', JavaExec) {
  classpath = sourceSets.main.runtimeClasspath

  mainClass = "de.monticore.umlstatecharts/UMLStatechartsTool"

  args("-i", "${testSCGenDir}/resources/examples/DoorExample.sc",
      "-gen", "${testSCOutDir}",
      "-hcp", "${testSCGenDir}/java")
}

generateSC.dependsOn compileJava
compileTestscgenJava.dependsOn generateSC
check.dependsOn testscgenClasses

tasks.withType(Test).configureEach {
  maxParallelForks = Runtime.runtime.availableProcessors() ?: 1
}

tasks.withType(JavaCompile).configureEach {
  options.fork = true
  options.encoding = "UTF-8"
  options.deprecation = false
  options.warnings = false
  options.headerOutputDirectory.convention(null)
}

// all in one tool-jar
shadowJar {
    manifest {
        attributes "Main-Class": "de.monticore.umlstatecharts.UML${archiveBaseName.get().capitalize()}Tool"
    }
    archiveClassifier = "mc-tool"
    archiveFileName = "MC${archiveBaseName.get().capitalize()}.${archiveExtension.get()}"
}

if (withTR) {
  // all in one (umlp) tf-tool-jar
  tasks.register('uMLSCTransGenerator', ShadowJar) {
    onlyIf { withTR }
    dependsOn shadowJar
    group = "shadow"
    manifest.attributes 'Main-Class': 'de.monticore.tr.UMLStatechartsTFGenTool'
    archiveFileName = "UMLSCTransGenerator.jar"
    archiveClassifier = "umltfgen"
    from zipTree(shadowJar.archiveFile)
    from zipTree(trafoJar.archiveFile)
    configurations += [project.configurations.trafoRuntimeClasspath]
  }

  artifacts {
    umlscTransGenerator(uMLSCTransGenerator.archiveFile) {
      builtBy uMLSCTransGenerator
    }
  }

  // all in one (triggered) tf-tool-jar
  tasks.register('triggeredSCTransGenerator', ShadowJar) {
    onlyIf { withTR }
    dependsOn shadowJar
    group = "shadow"
    manifest.attributes 'Main-Class': 'de.monticore.tr.TriggeredStatechartsTFGenTool'
    archiveFileName = "TriggeredSCTransGenerator.jar"
    archiveClassifier = "triggeredtfgen"
    from zipTree(shadowJar.archiveFile)
    from zipTree(trafoJar.archiveFile)
    configurations += [project.configurations.trafoRuntimeClasspath]
  }
}

tasks.register('testReport', TestReport) {
  destinationDirectory = layout.buildDirectory.dir("reports/allTests")
  // Include the results from the 'test' task
  dependsOn(tasks.withType(Test))
  testResults.from(tasks.withType(Test).collect { it.binaryResultsDirectory})
}

/**
 * Integration with MLC language and tool
 */
tasks.register('checkArtifacts') { group = 'mlc' }
configurations { MLC }
dependencies { MLC("de.monticore.lang:mlc-tool:$mlc_version") }
def modelPath = []
configurations.compileClasspath.resolve().each { modelPath.addAll(["-mp", it.toString()]) }
configurations.grammarSymbolDependencies.resolve().each { modelPath.addAll(["-mp", it.toString()]) }
modelPath.addAll(["-mp", "$projectDir/src/main/grammars/de/monticore"])

// two tasks per MLC file
fileTree("src").matching { include '**/*.mlc' }.each {
    def f = it
    def mlcName = it.getName().substring(0, it.getName().lastIndexOf('.'))

  tasks.register("showArtifacts${mlcName}", JavaExec) {
    classpath = configurations.MLC
    group = 'mlc'
    mainClass = 'de.monticore.mlc.MLCTool'
    args = ["-input", f, "-projectDir", projectDir, "-s", "-all"]
    args += modelPath
    dependsOn("generateMCGrammars")
  }

  tasks.register("checkArtifacts${mlcName}", JavaExec) {
    classpath = configurations.MLC
    group = 'mlc'
    mainClass = 'de.monticore.mlc.MLCTool'
    args = ["-input", f, "-projectDir", projectDir, "-s", "-check"]
    args += modelPath
    dependsOn("generateMCGrammars")
  }
  checkArtifacts.dependsOn("checkArtifacts${mlcName}")
}    // end integration with MLC

tasks.withType(JavaExec).configureEach {
  javaLauncher = javaToolchains.launcherFor {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

java {
  withSourcesJar()
  // Deprecated feature, published for compatibility reasons
  registerFeature('grammars') {
    usingSourceSet(sourceSets.grammarsForVariant)
  }
}

sourcesJar.dependsOn project.collect { it.tasks.withType(MCTask) }

jar.dependsOn grammarsJar, shadowJar

if (withTR) {
  build.dependsOn triggeredSCTransGenerator, uMLSCTransGenerator
}

// configure deployment
publishing {
    // configure what artifacts to publish
    publications {
      mavenJava(MavenPublication) {
        from components.java
      }
    }
    repositories.maven {
        credentials.username = mavenUser
        credentials.password = mavenPassword
        def releasesRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/monticore-releases/"
        def snapshotsRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/monticore-snapshots/"
        url = version.endsWith("SNAPSHOT") ? snapshotsRepoUrl : releasesRepoUrl
    }
}

tasks.register('buildAll', GradleBuild) {
  tasks = ['build']
}

defaultTasks('build')
