mavenUser=${username}
mavenPassword=${password}
repo=https://nexus.se.rwth-aachen.de/content/groups/public
org.gradle.vfs.watch=true

mc_version=7.9.0-SNAPSHOT
# TODO: Outdated MLC due to circular dependency
mlc_version=7.8.0-SNAPSHOT

version=7.9.0-SNAPSHOT

junit_version=5.13.4
shadow_plugin_version=8.3.11
commons_lang3_version=3.18.0
groovy_version=4.0.28

group=de.monticore.lang

org.gradle.jvmargs=-Xmx3072m

genTR=false

useLocalRepo=false
