/* (c) https://github.com/MontiCore/monticore */
plugins {
  id "java"
  id "de.monticore.generator-withtr" version "$mc_version" // MontiCore Plugin (with TR support)
}

description = "sc-trans-test"
layout.buildDirectory = layout.projectDirectory.dir("target")

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

configurations {
  scGenerator
}

dependencies {
  testImplementation "org.junit.jupiter:junit-jupiter:$junit_version"
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")

  // Depend on the rootProject (the module actually defining statecharts)
  grammar rootProject

  // add the dependency to sub1s trafos to the trafoGrammar config,
  // adding it as a dependency to the trafo publication
  // Note: This dependency will be substituted by its subproject
  grammar "${project.getGroup()}:statecharts-trafo:${project.getVersion()}"

  // use the grammar configuration (for trafos) to add transitive dependencies of :sub1
  grammar project(path: rootProject.path, configuration: 'trafoGrammar')

  // add the compiled trafo java classes of the subproject to the classpath
  implementation files(rootProject.sourceSets.trafo.output.classesDirs)
  scGenerator project(path: rootProject.path, configuration: "umlscTransGenerator")
}

configurations.configureEach {
  resolutionStrategy.dependencySubstitution {
    // Substitute statecharts-trafo with the actual (live) project,
    // loosing the trafo configuration information (requiring the project(path:...,configuration:...) dependencies above)
    substitute module("${project.getGroup()}:statecharts-trafo") using project(rootProject.path)
  }
}

repositories {
  mavenLocal()
  maven {
    credentials.username = mavenUser
    credentials.password = mavenPassword
    url = repo
  }
}

test {
  useJUnitPlatform()
}


tasks.register('generateStatechartTRRules') {}

def testModelsDir = layout.projectDirectory.dir("src/main/models/uml").asFile
def outDir = layout.buildDirectory.dir("generated-trafo-sources").get().asFile.absolutePath

fileTree(dir: testModelsDir, include: "**/*.mtr").each { File g ->
  def baseName = g.getName().substring(0, g.getName().lastIndexOf('.'))
  def taskName = "generateUMLStatechartTRRules${baseName}"

  def genTask = tasks.register(taskName, JavaExec) {
    group = "montitrans"
    classpath = configurations.scGenerator
    mainClass.set("de.monticore.tr.UMLStatechartsTFGenTool")
    args("-i", g.absolutePath,
        "-o", outDir)
  }

  tasks.named("generateStatechartTRRules") {
    dependsOn(genTask)
  }
}

tasks.withType(JavaExec).configureEach {
  javaLauncher = javaToolchains.launcherFor {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

sourceSets.test.java.srcDirs += ["$buildDir/generated-trafo-sources"]


compileTestJava.dependsOn += generateStatechartTRRules

// Fixes issue with java plugin in projects without resources
compileTestJava.doFirst { mkdir sourceSets.test.output.resourcesDir }

tasks.withType(Test).configureEach {
  maxParallelForks = Runtime.runtime.availableProcessors() ?: 1
}


java {
  withSourcesJar()
}


tasks.register('buildAll', GradleBuild) {
  tasks = ['build']
}
